import type { Metadata } from "next";
import "./globals.css";
import Global from "@/components/global/Global";

export const metadata: Metadata = {
  title: "Apurbo Roy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Global />
      <body className="bg-[#1B1D26] text-[white]">{children}</body>
    </html>
  );
}
